import { BusinessConfig } from './types';

/**
 * PRODUCTION CONFIGURATION
 * This file is automatically generated by the Build Engine.
 * It follows a locked schema to ensure runtime stability.
 */
export const config: BusinessConfig = {
  "companyName": "EWASH",
  "city": "Casablanca",
  "heroTitle": "Premium Eco-Friendly Car Wash in Casablanca",
  "heroSubtitle": "Professional auto detailing and mobile wash services that bring the shine back to your vehicle.",
  "phone": "0611204502",
  "whatsapp": "+212611204502",
  "email": "contact@ewash-casablanca.ma",
  "theme": "light",
  "colors": {
    "primary": "#2563eb"
  },
  "services": [
    "Exterior Hand Wash & Wax",
    "Interior Deep Cleaning & Vacuuming",
    "Engine Bay Detailing",
    "Ceramic Coating",
    "Headlight Restoration"
  ],
  "packages": [
    {
      "price": "150 MAD",
      "name": "Basic Wash",
      "features": [
        "Exterior Hand Wash",
        "Tire Shine",
        "Windows Cleaned"
      ]
    },
    {
      "name": "Premium Wash",
      "price": "300 MAD",
      "features": [
        "Interior Vacuuming",
        "Dashboard Wipedown",
        "Premium Spray Wax"
      ]
    },
    {
      "features": [
        "Shampoo Carpets",
        "Engine Bay Wash",
        "Clay Bar Treatment"
      ],
      "name": "Ultimate Detailing",
      "price": "800 MAD"
    }
  ],
  "reviews": [
    {
      "author": "Client Satisfait",
      "text": "Service impeccable !",
      "rating": 5,
      "date": "Récemment"
    }
  ],
  "stats": [
    {
      "label": "Années d'expérience",
      "value": "10+"
    },
    {
      "label": "Clients satisfaits",
      "value": "500+"
    }
  ],
  "gallery_images": [],
  "before_after_images": []
};
