import { BusinessConfig } from './types';

// Helper to ensure array stability - injected for safety
const safeArray = <T>(arr: T[] | undefined | null): T[] => Array.isArray(arr) ? arr : [];

/**
 * PRODUCTION CONFIGURATION
 * This file is automatically generated by the Build Engine.
 * All arrays are guaranteed to be present to prevent runtime crashes.
 */
export const config: BusinessConfig = {
  "businessName": "EWASH",
  "city": "Casablanca",
  "whatsapp": "+212611204502",
  "phone": "0611204502",
  "email": "contact@ewash-casablanca.ma",
  "address": "Maarif, Casablanca",
  "heroTitle": "Premium Car Wash & Auto Detailing in Casablanca",
  "heroSubtitle": "Experience top-tier vehicle cleaning, interior detailing, and polishing services that bring the showroom shine back to your car.",
  "theme": "light",
  "category": "STATION DE LAVAGE AUTOMOBILE",
  "services": [
    "Exterior Hand Wash & Wax",
    "Complete Interior Deep Cleaning",
    "Engine Bay Cleaning",
    "Paint Correction & Polishing",
    "Ceramic Coating Application"
  ],
  "pricing": [
    {
      "price": "150 MAD",
      "name": "Basic Wash"
    },
    {
      "price": "450 MAD",
      "name": "Premium Detail"
    },
    {
      "price": "900 MAD",
      "name": "Ultimate Shine"
    }
  ],
  "testimonials": [
    {
      "name": "Client Satisfait",
      "role": "Client",
      "text": "Service impeccable !"
    }
  ],
  "heroImage": "https://images.unsplash.com/photo-1521791136064-7986c2923216?auto=format&fit=crop&q=80&w=2069&keywords=business,modern",
  "before_after_images": [
    {
      "before": "https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?auto=format&fit=crop&q=80&w=1000",
      "after": "https://images.unsplash.com/photo-1605515298946-d062f2e9da53?auto=format&fit=crop&q=80&w=1000",
      "label": "Exemple de réalisation"
    }
  ],
  "gallery_images": [
    "https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?auto=format&fit=crop&q=80&w=1000",
    "https://images.unsplash.com/photo-1605515298946-d062f2e9da53?auto=format&fit=crop&q=80&w=1000",
    "https://images.unsplash.com/photo-1552930294-6b595f4c2974?auto=format&fit=crop&q=80&w=1000"
  ],
  "reviews": [
    {
      "author": "Client Satisfait",
      "text": "Service exceptionnel et très professionnel !",
      "rating": 5,
      "date": "Récemment"
    },
    {
      "author": "Marie D.",
      "text": "Très bonne expérience, je recommande vivement.",
      "rating": 5,
      "date": "Il y a 1 mois"
    }
  ],
  "packages": [
    {
      "price": "150 MAD",
      "name": "Basic Wash"
    },
    {
      "price": "450 MAD",
      "name": "Premium Detail"
    },
    {
      "price": "900 MAD",
      "name": "Ultimate Shine"
    }
  ],
  "stats": [
    {
      "label": "Années d'expérience",
      "value": "10+"
    },
    {
      "label": "Clients satisfaits",
      "value": "500+"
    },
    {
      "label": "Projets terminés",
      "value": "1200+"
    }
  ],
  "features": [
    "Expertise Locale",
    "Matériel de Pointe",
    "Satisfaction Garantie"
  ],
  "social_links": [
    {
      "platform": "facebook",
      "url": "#"
    },
    {
      "platform": "instagram",
      "url": "#"
    }
  ],
  "gallery": [
    "https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?auto=format&fit=crop&q=80&w=1000",
    "https://images.unsplash.com/photo-1605515298946-d062f2e9da53?auto=format&fit=crop&q=80&w=1000",
    "https://images.unsplash.com/photo-1552930294-6b595f4c2974?auto=format&fit=crop&q=80&w=1000"
  ]
};

// Map-safe exports for components that might use direct imports
export const services = safeArray(config.services);
export const reviews = safeArray(config.reviews);
export const packages = safeArray(config.packages);
export const gallery = safeArray(config.gallery_images);
export const stats = safeArray(config.stats);
export const features = safeArray(config.features);
