import { BusinessConfig } from './types';

/**
 * PRODUCTION CONFIGURATION
 * This file is automatically generated by the Build Engine.
 * It follows a locked schema to ensure runtime stability.
 */
export const config: BusinessConfig = {
  "companyName": "EWASH",
  "city": "Casablanca",
  "heroTitle": "Premium Car Wash & Auto Detailing in Casablanca",
  "heroSubtitle": "Experience top-tier vehicle cleaning, interior detailing, and polishing services that bring the showroom shine back to your car.",
  "phone": "0611204502",
  "whatsapp": "+212611204502",
  "email": "contact@ewash-casablanca.ma",
  "theme": "light",
  "colors": {
    "primary": "#2563eb"
  },
  "services": [
    "Exterior Hand Wash & Wax",
    "Complete Interior Deep Cleaning",
    "Engine Bay Cleaning",
    "Paint Correction & Polishing",
    "Ceramic Coating Application"
  ],
  "packages": [
    {
      "price": "150 MAD",
      "name": "Basic Wash"
    },
    {
      "price": "450 MAD",
      "name": "Premium Detail"
    },
    {
      "price": "900 MAD",
      "name": "Ultimate Shine"
    }
  ],
  "reviews": [
    {
      "author": "Client Satisfait",
      "text": "Service impeccable !",
      "rating": 5,
      "date": "Récemment"
    }
  ],
  "stats": [
    {
      "label": "Années d'expérience",
      "value": "10+"
    },
    {
      "label": "Clients satisfaits",
      "value": "500+"
    }
  ],
  "gallery_images": [],
  "before_after_images": []
};
